# .github/workflows/dns-watchdog.yml
name: Fortress DNS Watchdog

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  watchdog:
    runs-on: ubuntu-latest
    env:
      ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install python-dotenv requests
      - name: Run watchdog
        run: python fortress-dns-secure-auto/dns_watchdog.py